FROM mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye

# Install Azure CLI
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# Install Azure Static Web Apps CLI
RUN npm install -g @azure/static-web-apps-cli@2.0.6